/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AnalyticsRouteImport } from './routes/analytics'
import { Route as AuthorityAlertsRouteImport } from './routes/authority-alerts'
import { Route as CitizenReportsRouteImport } from './routes/citizen-reports'
import { Route as ForecastRouteImport } from './routes/forecast'
import { Route as ResourcesRouteImport } from './routes/resources'
import { Route as SafeRoutesRouteImport } from './routes/safe-routes'
import { Route as SensorsRouteImport } from './routes/sensors'
import { Route as SheltersRouteImport } from './routes/shelters'
import { Route as SimulatorRouteImport } from './routes/simulator'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AnalyticsRoute = AnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthorityAlertsRoute = AuthorityAlertsRouteImport.update({
  id: '/authority-alerts',
  path: '/authority-alerts',
  getParentRoute: () => rootRouteImport,
} as any)
const CitizenReportsRoute = CitizenReportsRouteImport.update({
  id: '/citizen-reports',
  path: '/citizen-reports',
  getParentRoute: () => rootRouteImport,
} as any)
const ForecastRoute = ForecastRouteImport.update({
  id: '/forecast',
  path: '/forecast',
  getParentRoute: () => rootRouteImport,
} as any)
const ResourcesRoute = ResourcesRouteImport.update({
  id: '/resources',
  path: '/resources',
  getParentRoute: () => rootRouteImport,
} as any)
const SafeRoutesRoute = SafeRoutesRouteImport.update({
  id: '/safe-routes',
  path: '/safe-routes',
  getParentRoute: () => rootRouteImport,
} as any)
const SensorsRoute = SensorsRouteImport.update({
  id: '/sensors',
  path: '/sensors',
  getParentRoute: () => rootRouteImport,
} as any)
const SheltersRoute = SheltersRouteImport.update({
  id: '/shelters',
  path: '/shelters',
  getParentRoute: () => rootRouteImport,
} as any)
const SimulatorRoute = SimulatorRouteImport.update({
  id: '/simulator',
  path: '/simulator',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/authority-alerts': typeof AuthorityAlertsRoute
  '/citizen-reports': typeof CitizenReportsRoute
  '/forecast': typeof ForecastRoute
  '/resources': typeof ResourcesRoute
  '/safe-routes': typeof SafeRoutesRoute
  '/sensors': typeof SensorsRoute
  '/shelters': typeof SheltersRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/authority-alerts': typeof AuthorityAlertsRoute
  '/citizen-reports': typeof CitizenReportsRoute
  '/forecast': typeof ForecastRoute
  '/resources': typeof ResourcesRoute
  '/safe-routes': typeof SafeRoutesRoute
  '/sensors': typeof SensorsRoute
  '/shelters': typeof SheltersRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/analytics': typeof AnalyticsRoute
  '/authority-alerts': typeof AuthorityAlertsRoute
  '/citizen-reports': typeof CitizenReportsRoute
  '/forecast': typeof ForecastRoute
  '/resources': typeof ResourcesRoute
  '/safe-routes': typeof SafeRoutesRoute
  '/sensors': typeof SensorsRoute
  '/shelters': typeof SheltersRoute
  '/simulator': typeof SimulatorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/authority-alerts'
    | '/citizen-reports'
    | '/forecast'
    | '/resources'
    | '/safe-routes'
    | '/sensors'
    | '/shelters'
    | '/simulator'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/analytics'
    | '/authority-alerts'
    | '/citizen-reports'
    | '/forecast'
    | '/resources'
    | '/safe-routes'
    | '/sensors'
    | '/shelters'
    | '/simulator'
  id:
    | '__root__'
    | '/'
    | '/analytics'
    | '/authority-alerts'
    | '/citizen-reports'
    | '/forecast'
    | '/resources'
    | '/safe-routes'
    | '/sensors'
    | '/shelters'
    | '/simulator'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AnalyticsRoute: typeof AnalyticsRoute
  AuthorityAlertsRoute: typeof AuthorityAlertsRoute
  CitizenReportsRoute: typeof CitizenReportsRoute
  ForecastRoute: typeof ForecastRoute
  ResourcesRoute: typeof ResourcesRoute
  SafeRoutesRoute: typeof SafeRoutesRoute
  SensorsRoute: typeof SensorsRoute
  SheltersRoute: typeof SheltersRoute
  SimulatorRoute: typeof SimulatorRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/analytics': {
      id: '/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AnalyticsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/authority-alerts': {
      id: '/authority-alerts'
      path: '/authority-alerts'
      fullPath: '/authority-alerts'
      preLoaderRoute: typeof AuthorityAlertsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/citizen-reports': {
      id: '/citizen-reports'
      path: '/citizen-reports'
      fullPath: '/citizen-reports'
      preLoaderRoute: typeof CitizenReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forecast': {
      id: '/forecast'
      path: '/forecast'
      fullPath: '/forecast'
      preLoaderRoute: typeof ForecastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resources': {
      id: '/resources'
      path: '/resources'
      fullPath: '/resources'
      preLoaderRoute: typeof ResourcesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/safe-routes': {
      id: '/safe-routes'
      path: '/safe-routes'
      fullPath: '/safe-routes'
      preLoaderRoute: typeof SafeRoutesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sensors': {
      id: '/sensors'
      path: '/sensors'
      fullPath: '/sensors'
      preLoaderRoute: typeof SensorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/shelters': {
      id: '/shelters'
      path: '/shelters'
      fullPath: '/shelters'
      preLoaderRoute: typeof SheltersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/simulator': {
      id: '/simulator'
      path: '/simulator'
      fullPath: '/simulator'
      preLoaderRoute: typeof SimulatorRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AnalyticsRoute: AnalyticsRoute,
  AuthorityAlertsRoute: AuthorityAlertsRoute,
  CitizenReportsRoute: CitizenReportsRoute,
  ForecastRoute: ForecastRoute,
  ResourcesRoute: ResourcesRoute,
  SafeRoutesRoute: SafeRoutesRoute,
  SensorsRoute: SensorsRoute,
  SheltersRoute: SheltersRoute,
  SimulatorRoute: SimulatorRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
